if(NOT WASM_BUILD)
    set(SHP_SOURCE_DIRECTORY_FOR_INCLUDE_PATHS "${CMAKE_SOURCE_DIR}") #SPHinXsys
else()
    set(SHP_SOURCE_DIRECTORY_FOR_INCLUDE_PATHS "${CMAKE_SOURCE_DIR}") #SPH_to_JS/SPHinXsys_Virtonomy/SPHinXsys
endif()

SET(ONETBB_HEADER_DIRECTORY
    "${SHP_SOURCE_DIRECTORY_FOR_INCLUDE_PATHS}/oneTBB/include"
)